# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruitclub', '0003_auto_20170208_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='slideshow', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SlideShowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='slideshow')),
                ('caption', models.CharField(max_length=256, null=True)),
                ('url', models.URLField()),
                ('slideshow', models.ForeignKey(default='slideshow', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fruitclub.SlideShow')),
            ],
        ),
    ]
