# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitclub', '0004_slideshow_slideshowimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideShow',
            new_name='ImageGroup',
        ),
    ]
