# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitclub', '0006_auto_20170209_0119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
