# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitclub', '0010_auto_20170209_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
