# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
